name: afeefa_handloom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  animated_text_kit: ^4.2.1
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  flutter:
    sdk: flutter
  flutter_circle_color_picker: ^0.3.0
  flutter_countdown_timer: ^4.1.0
  flutter_image_compress: ^1.1.0
  get: 4.6.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  hexcolor: ^2.0.6
  http: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+6
  path_provider: ^2.0.8
  pinput: ^1.2.2
  share_plus: ^3.0.4
  simple_gradient_text: ^1.2.2
  zoom_pinch_overlay: ^1.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
